### ISSUE TITLE
Add support for Variables in Jupyter VS Code extension

### ISSUE THREAD

**Issue by logankilpatrick** [julia-vscode/julia-vscode#2390] opened 2021-08-22 13:40 UTC
I already have an issue open here: https://github.com/microsoft/vscode-jupyter/issues/7224 but thought I would cross post it since it looks like we might already have the code for this working.

**Comment by davidanthoff** [comment] 2021-08-22 19:11
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/2240 :)

**Closed by davidanthoff** 2021-08-22 19:11 UTC
