### ISSUE TITLE
missing debugging capabilities 

### ISSUE THREAD

**Issue by YousefSaber** [julia-vscode/julia-vscode#1021] opened 2020-02-27 21:26 UTC
your extension provides an excellent auto code support and syntax highlighting but what about debugging I can't debug my Julia code in VSCode please provide this feature in your extension

**Comment by davidanthoff** [comment] 2020-02-27 21:28
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/125.

**Closed by davidanthoff** 2020-02-27 21:28 UTC
