### ISSUE TITLE
A request about jupyter function.

### ISSUE THREAD

**Issue by Photonico** [julia-vscode/julia-vscode#1040] opened 2020-03-08 19:02 UTC
The extension python-vscode can already run the ipynb file with complete IPython functions.
But it cannot connect to Julia kernel. 
Will you add the jupyter function to this extension?

**Comment by davidanthoff** [comment] 2020-03-08 19:08
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/874.

**Closed by davidanthoff** 2020-03-08 19:08 UTC
