### ISSUE TITLE
Format file corrupts files

### ISSUE THREAD

**Issue by baggepinnen** [julia-vscode/julia-vscode#1725] opened 2020-10-30 05:58 UTC
I have since switching to vscode thought I have started to accidentally paste snippets of code into my editors, making my code corrupt. It turns out that it is `ctrl+shift+I` in vscode that corrupts my files, manual calls to `JuliaFormatter.format_file` do not suffer from this problem. Below is an example, where the end of the outer `map` operation is messed up by the formatter. The part
```
    direction = repeat(1:4, n_tests)
    # pos = repeat(1:3, inner=4*n_vib_conf)
    pos = repeat(1:3, inner=4, outer=n_vib_conf)
```
is showhow copied and inserted twice, making the code corrupt.
```julia
log_frames = map(enumerate(logfiles)) do (logi, logfile)
    N = length(ifreqs)
    tolength(x, N) = resample(x, (N + eps(float(N))) / (length(x) - eps(float(N))))[1:N]
    fig1 = plot(tolength(vel, N) .* 10 .+ 20, lab="vel (shift and scale)")
    scatter!(ifreqs, lab="Inst. freq in acc", yticks=0:5:50)
    fig2 = plot(spectrogram(aica, 1024, fs=1000, window=hanning), yscale=:identity, ylims=(0,90), yticks=0:5:90, title="a_{ica] $logfile", clims=(-12, -3.2))
    plot(fig1, fig2, layout=(2,1)) |> display
    return

    ##

    ## Plot step response energies

    E = map(snippets) do s
        var(s[110:end])
    end
    E = copy(reshape(E, 4, :)')

    E = map(snippets) do s
        var(s[110:end])
    end
    direction = repeat(1:4, n_tests)
    # pos = repeat(1:3, inner=4*n_vib_conf)
    pos = repeat(1:3, inner=4, outer=n_vib_conf)
    # amplitude = (0:length(snippets)-1) .÷ 4 .+1

    logdata = DataFrame(:direction => direction, :energy => E, :pos => pos, :logfile => fill(logfile, length(E)), :snippets => snippets)

    logdata
end

```
is formatted to
```julia
log_frames = map(enumerate(logfiles)) do (logi, logfile)
    N = length(ifreqs)
    tolength(x, N) = resample(x, (N + eps(float(N))) / (length(x) - eps(float(N))))[1:N]
    fig1 = plot(tolength(vel, N) .* 10 .+ 20, lab = "vel (shift and scale)")
    scatter!(ifreqs, lab = "Inst. freq in acc", yticks = 0:5:50)
    fig2 = plot(
        spectrogram(aica, 1024, fs = 1000, window = hanning),
        yscale = :identity,
        ylims = (0, 90),
        yticks = 0:5:90,
        title = "a_{ica] $logfile",
        clims = (-12, -3.2),
    )
    plot(fig1, fig2, layout = (2, 1)) |> display
    return

    ##

    ## Plot step response energies

    E = map(snippets) do s
        var(s[110:end])
    end
    E = copy(reshape(E, 4, :)')

    E = map(snippets) do s
        var(s[110:end])
    end
    direction = repeat(1:4, n_tests)
    # pos = repeat(1:3, inner=4*n_vib_conf)
    pos = repeat(1:3, inner=4, outer=n_vib_conf)
    # amplitude = (0:length(snippets)-1) .÷ 4 .+1

        var(s[110:end])
    end
    direction = repeat(1:4, n_tests)
    # pos = repeat(1:3, inner=4*n_vib_conf)
    pos = repeat(1:3, inner = 4, outer = n_vib_conf)
    # amplitude = (0:length(snippets)-1) .÷ 4 .+1

    logdata = DataFrame(
        :direction => direction,
        :energy => E,
        :pos => pos,
        :logfile => fill(logfile, length(E)),
        :snippets => snippets,
    )

    logdata
end
```
I submitted a comment on https://github.com/domluna/JuliaFormatter.jl/issues/290 but it seems that vscode is the culprit, seeing how `format_file` works okay.

**Comment by aviatesk** [comment] 2020-10-30 06:08
We don't use JuliaFormatter.jl, actually. See https://github.com/julia-vscode/LanguageServer.jl/pull/759

**Comment by baggepinnen** [comment] 2020-10-30 06:22
If this issue is to be considered closed, maybe the option to use the vscode formatter should be removed from the plugin since it clearly corrupts the users code?

**Comment by davidanthoff** [comment] 2021-02-02 21:30
This somehow slipped by. @ZacLN could you take a look and decide whether we need to do something about this?

**Comment by ZacLN** [comment] 2021-02-02 21:43
I can't replicate (on insiders), so nothing we can do right now.

**Comment by baggepinnen** [comment] 2021-02-03 07:45
Yep, definitely still a problem on the insider version. Not all files trigger this, but one of the ones I tested on did

**Comment by davidanthoff** [comment] 2021-02-03 17:28
@baggepinnen could you share the file with @ZacLN somehow?

**Comment by NicholasWMRitchie** [comment] 2021-02-10 13:06
Using the default Julia code formater on Visual Code Studio, I get corruption every time on the last code line if there is not an empty line at the end of the file.   If I add an empty line below the last code line, there is no corruption.

**Comment by samuela** [comment] 2021-02-11 07:45
> Initially I had thought I was using the default formatter however, upon further investigation, it does appear that I'm using Julia Formatter 0.4.0. I'm not sure if I installed this or whether it was installed when I installed the Julia support. (I just don't recall.) Switching to the other un-named (?default?) formatter does not produce this error.

What is the other un-named formatter? How do I use it?

**Comment by davidanthoff** [comment] 2021-02-11 08:17
The formatter that ships with the VS Code Julia extension is DocumentFormat.jl. I'm confused now, is this issue here actually about a bug in DocumentFormat.jl, or in JuliaFormatter.jl? If the latter, we should just close this issue here because that is not part of the extension.

**Comment by rkurchin** [comment] 2021-05-17 16:44
I've been having some issues as well that are tricky to create an MWE of but I suspect this issue might actually belong in this repo --> https://github.com/singularitti/vscode-julia-formatter

and maybe even is a duplicate of https://github.com/singularitti/vscode-julia-formatter/issues/28

**Comment by pfitzseb** [comment] 2021-11-04 18:42
Next version of the extension should fix this, since it uses JuliaFormatter.

**Closed by pfitzseb** 2021-11-04 18:42 UTC
Labels: bug, needs more info, area-ls-formatting
