### ISSUE TITLE
Code completion not working for local module

### ISSUE THREAD

**Issue by harrysw1729** [julia-vscode/julia-vscode#1822] opened 2020-12-18 03:42 UTC
I am quite new to Julia and the Julia VS code extension. Please forgive me if the question is trivial or confusing.

I have a working directory with a module called Tmp.
```
Project
|
+-- test.jl
|
+-- Tmp
    |
    +-- src
        |
        +-- Tmp.jl
    +-- Project.toml
```

`Tmp.jl` has the following code.
```julia
module Tmp

export f

f(a, b) = a + b

end
```

In the working directory, I ran the following code in REPL to load `Tmp`.
```julia
if pwd() ∉ LOAD_PATH
    push!(LOAD_PATH, pwd())
end

using Tmp
```

The loading was successful. However, when I typed `f(` in `test.jl`, there was no completion suggestion for `f`, which is defined in `Tmp`.

**Comment by pfitzseb** [comment] 2020-12-22 16:47
I think the problem here is that we can't analyze the `LOAD_PATH` modification there. You should be able to click on the `Julia env` entry and then select `Project/Tmp`, after which you _should_ get completions (there might be a bug somewhere that stops that from working as intended though).

**Comment by davidanthoff** [comment] 2021-02-21 03:22
Yeah, I'm going to close this as a duplicate: we already have an issue that tracks support for custom `LOAD_PATH` values.

**Closed by davidanthoff** 2021-02-21 03:22 UTC
