### ISSUE TITLE
TestItems runner doesn't pick up changes to Project.toml

### ISSUE THREAD

**Issue by NHDaly** [julia-vscode/julia-vscode#3483] opened 2023-12-05 15:50 UTC
The TestItems runner doesn't pick up changes to Project.toml. It should evict its cache when the Project.toml or Manifest.toml are edited.

- If you create a new package, and forget to add `Test` as a dependency
- Then you run a testitem
- You get the following error:
    - ```
        Unable to load the `Test` package. Please ensure that `Test` is listed as a test dependency in the Project.toml for the package.
        ```
- So then you add `Test` via `] add Test`, and now it's in the Project.toml, but
- Rerunning the same testitem still fails in the same way.

Thanks! :) I'm really enjoying the testing experience in VSCode!!

**Comment by NHDaly** [comment] 2023-12-05 15:51
(Reloading the window fixes this of course.)

**Comment by davidanthoff** [comment] 2024-06-06 23:13
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/3022.

**Closed by davidanthoff** 2024-06-06 23:13 UTC
