### ISSUE TITLE
treerender worldage error

### ISSUE THREAD

**Issue by jonniedie** [julia-vscode/julia-vscode#1408] opened 2020-06-26 18:07 UTC
Since the update, I've been getting this error. It was occasional at first, but now it's all the time. `ComponentArray`s aren't the only type I've ran into this issue on, `LabelledArrays`s, `OffsetArrays`, etc. are the same.

```julia
julia> using ComponentArrays

julia> ca = ComponentArray(a=5, b=[5, 1, 6])
ComponentVector{Int64}(a = 5, b = [5, 1, 6])Internal Error: 
ERROR: 
MethodError: no method matching size(::ComponentArray{Int64,1,Array{Int64,1},Tuple{Axis{(a = 1, b = 2:4)}}})
The applicable method may be too new: running in world age 27177, while current world is 27181.
Closest candidates are:
  size(::ComponentArray) at C:\Users\jdiegelm\.julia\dev\ComponentArrays\src\componentarray.jl:258 (method too new to be called from this world context.)
  size(::AbstractArray{T,N}, ::Any) where {T, N} at abstractarray.jl:38
  size(::BitArray{1}) at bitarray.jl:99
julia> 
Stacktrace:
julia>  [1] treerender(::ComponentArray{Int64,1,Array{Int64,1},Tuple{Axis{(a = 1, b = 2:4)}}}) at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\VSCodeServer\src\trees.jl:125
 [2] treerender(::VSCodeServer.SubTree) at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\VSCodeServer\src\trees.jl:54
 [3] repl_getvariables_request(::VSCodeServer.JSONRPC.JSONRPCEndpoint, ::Nothing) at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\VSCodeServer\src\request_handlers.jl:88
 [4] dispatch_msg(::VSCodeServer.JSONRPC.JSONRPCEndpoint, ::VSCodeServer.JSONRPC.MsgDispatcher, ::Dict{String,Any}) at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\JSONRPC\src\typed.jl:63
 [5] macro expansion at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\VSCodeServer\src\VSCodeServer.jl:83 [inlined]
 [6] (::VSCodeServer.var"#53#55"{Bool,String})() at .\task.jl:358
Internal Error: ERROR: MethodError: no method matching size(::ComponentArray{Int64,1,Array{Int64,1},Tuple{Axis{(a = 1, b = 2:4)}}})
The applicable method may be too new: running in world age 27177, while current world is 27181.
Closest candidates are:
  size(::ComponentArray) at C:\Users\jdiegelm\.julia\dev\ComponentArrays\src\componentarray.jl:258 (method too new to be called from this world context.)
  size(::AbstractArray{T,N}, ::Any) where {T, N} at abstractarray.jl:38
  size(::BitArray{1}) at bitarray.jl:99
  ...
Stacktrace:
 [1] treerender(::ComponentArray{Int64,1,Array{Int64,1},Tuple{Axis{(a = 1, b = 2:4)}}}) at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\VSCodeServer\src\trees.jl:125
 [2] treerender(::VSCodeServer.SubTree) at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\VSCodeServer\src\trees.jl:54
 [3] repl_getvariables_request(::VSCodeServer.JSONRPC.JSONRPCEndpoint, ::Nothing) at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\VSCodeServer\src\request_handlers.jl:88
 [4] dispatch_msg(::VSCodeServer.JSONRPC.JSONRPCEndpoint, ::VSCodeServer.JSONRPC.MsgDispatcher, ::Dict{String,Any}) at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\JSONRPC\src\typed.jl:63
 [5] macro expansion at c:\Users\jdiegelm\.vscode\extensions\julialang.language-julia-0.16.8\scripts\packages\VSCodeServer\src\VSCodeServer.jl:83 [inlined]
 [6] (::VSCodeServer.var"#53#55"{Bool,String})() at .\task.jl:358
```

**Comment by sdewaele** [comment] 2020-06-26 18:13
I am getting this error, too. I can add `AxisArray`s to the list.

Is it right that this is caused by the new Julia Explorer? If so, is there a way to disable it, so that we can continue using the current version until this is resolved?

**Comment by davidanthoff** [comment] 2020-06-26 18:33
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/1404.

**Comment by davidanthoff** [comment] 2020-06-26 18:33
I don't think there is a way to disable things. We'll try to get a new version out ASAP.

**Closed by davidanthoff** 2020-06-26 18:33 UTC
