### ISSUE TITLE
Button to copy plot to clipboard 

### ISSUE THREAD

**Issue by jtrakk** [julia-vscode/julia-vscode#2034] opened 2021-03-12 23:20 UTC
I want to copy plot to clipboard. Related to https://github.com/julia-vscode/julia-vscode/issues/424

**Comment by davidanthoff** [comment] 2021-06-22 15:43
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/172.

**Closed by davidanthoff** 2021-06-22 15:43 UTC
Labels: area-plotpane, enhancement
