### ISSUE TITLE
julia.runLinter is not a registered configuration

### ISSUE THREAD

**Issue by tk3369** [julia-vscode/julia-vscode#1081] opened 2020-03-30 00:58 UTC
I tried to toggle linter but that didn't seem to work because the squirely underlines are still there.  I looked into various console logs and found the following error:

```
[2020-03-29 17:53:29.924] [renderer1] [error] Unable to write to User Settings because julia.runLinter is not a registered configuration.: Error: Unable to write to User Settings because julia.runLinter is not a registered configuration.
    at k.reject (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4744:465)
    at k.resolveAndValidate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4747:243)
    at k.doWriteConfiguration (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4741:722)
    at Object.factory (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4741:498)
    at u.consume (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:143:75)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:886
    at new Promise (<anonymous>)
    at u.queue (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:810)
    at k.writeConfiguration (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4741:483)
    at C.writeConfigurationValue (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4765:785)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4755:147
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I am using 0.15.18 with the following vscode versions:
```
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by tk3369** [comment] 2020-03-30 01:08
I just wiped the settings.json and start over.  The same exception appears when I trigger "Julia: Toggle Linter" command.

**Comment by davidanthoff** [comment] 2020-04-01 03:42
Something is messed up with the way we handle configuration. I just don't understand what the problem is yet...

**Comment by tk3369** [comment] 2020-04-03 16:28
I think I found the bug.

The package.json file registers `julia.lint.run`:
https://github.com/julia-vscode/julia-vscode/blob/dcbeaf7976f3d0a3516331a0153f56c4270179b3/package.json#L353

But, the code uses `julia.runLinter` instead:
https://github.com/julia-vscode/julia-vscode/blob/daada866d10aa7e7ab61a0aa0a30dddb39c958ea/src/smallcommands.ts#L13

**Comment by davidanthoff** [comment] 2020-04-04 21:18
Yes, that is a bug, just opened a PR that fixes it. But I think we have another problem, because this only affects the command that toggles things, while things are also going wrong if one doesn't use that command.

**Comment by hsm207** [comment] 2020-04-18 11:41
@davidanthoff could you please elaborate more about the new problem? I'd like to try to fix it.

**Comment by davidanthoff** [comment] 2020-04-27 09:56
I'm going to close this specific issue in favor of https://github.com/julia-vscode/julia-vscode/issues/1068 (as the main config fixing issue).

**Closed by davidanthoff** 2020-04-27 09:56 UTC
Labels: bug
