### ISSUE TITLE
cannot detect package correctly in local environment

### ISSUE THREAD

**Issue by Roger-luo** [julia-vscode/julia-vscode#867] opened 2019-09-25 21:01 UTC
I'm using v0.12.3 on MacOS, if you simply clone a package, e.g `IRTools`, then open it in terminal with `code IRTools`, the LS fails to detect the module

![image](https://user-images.githubusercontent.com/8445510/65639399-0e643180-dfb6-11e9-8654-605644172cca.png)

**Comment by davidanthoff** [comment] 2019-09-25 22:20
What is your active environment, as shown in the VS Code statusbar?

**Comment by Roger-luo** [comment] 2019-09-25 22:42
The active environment is IRTools.

**Comment by davidanthoff** [comment] 2019-09-26 03:05
Then that strikes me as a bug.

**Comment by singularitti** [comment] 2019-10-18 06:30
The same thing happens to me: VSCode cannot detect the package I am developing.

![image](https://user-images.githubusercontent.com/25192197/67070728-d84a4580-f14e-11e9-8cda-b6672029a765.png)

[`EquationsOfState.jl`](https://github.com/MineralsCloud/EquationsOfState.jl/blob/ada4474/src/Collections.jl#L11) is a local package I am developing. And I am in the environment of that package (activated, and instantiated). But VSCode cannot detect `EquationsOfState.jl` itself. As you can see, it can detect some 3rd-party deps, like `Unitful.jl`.

```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
```

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 12
```

Plugin version: 0.12.3

**Comment by DavidKMaslen** [comment] 2019-10-27 23:33
I have a similar problem. For me the extension is unable to detect installed Julia packages. When I open up the REPL it has no problem. So for example, if I type "using Test" into the Julia REPL for VS Code then it is ok, and finds the package, and I can use the contents. So the package is definitely there. But in my files if I type "using Test" then there is a squiggle under the "Test" and also under any functions that I use from the package. 

I'm on Windows 7 and using Julia 1.1.1, and on the status bar it says "Julia env: v1.1"

**Comment by DavidKMaslen** [comment] 2019-10-28 02:58
So my problem actually "went away". The thing that I did that I think worked was to clean out old directories of packages from installations of earlier versions of python. They were in directories marked with the version number (installed that way), so I'm not sure why they would have been a problem. In any case tidying up helped.

**Comment by Roger-luo** [comment] 2019-11-30 19:24
It seems when using the package environment, vscode plugin will only try to check the global environment (e.g v1.2) instead of package environment. The current Julia package loading mechanism is inside package environment, one can load packages in global environment as well. So I think the way to load it would be:

1. check package environment, load linter etc.
2. if not in package environment, check global environment `v1.x`
3. if not warns no reference

**Comment by davidanthoff** [comment] 2020-01-27 22:07
I'm closing this as a duplicate of https://github.com/julia-vscode/julia-vscode/issues/800.

**Closed by davidanthoff** 2020-01-27 22:07 UTC
Labels: area-ls-linter, bug
