### ISSUE TITLE
No output when running JET in REPL

### ISSUE THREAD

**Issue by jakobnissen** [julia-vscode/julia-vscode#2484] opened 2021-09-29 13:31 UTC
As discussed on Slack, running `@report_call foo()` in the REPL in VSCode will make the JET errors show up in VSCode's linter. Very cool!

But it was also confusing for me, as I'm used to seeing the JET in the REPL. To be clear, I prefer having it in the editor, but it just confused me.

Maybe it would be nice to print a message in the REPL whenever the user does `@report_call`, or another of the JET macros integrated with VSCode.

**Comment by pfitzseb** [comment] 2021-09-29 13:32
cc @aviatesk

**Comment by aviatesk** [comment] 2021-09-29 14:48
woa, we already have users of this hidden integration !

You can use [`vscode_console_output`](https://aviatesk.github.io/JET.jl/dev/config/#JET.VSCode.VSCodeConfig) configuration to get REPL printing also, like:
```julia
julia> @report_opt vscode_console_output=stdout sum("julia")
```

And now I wonder `vscode_console_output` might be better to specify `stdout` by default ?

**Comment by pfitzseb** [comment] 2021-09-29 15:05
We could also fix this here and call `display(REPLDisplay()/InlineDisplay(), result)` when the diagnostics mime type is hit.

**Comment by aviatesk** [comment] 2021-09-29 15:16
Yeah, it would be simpler if we can fix this on VSCode side and always enable REPL printing.

**Comment by pfitzseb** [comment] 2021-11-05 18:38
Fixed by https://github.com/julia-vscode/julia-vscode/pull/2536.

**Comment by jakobnissen** [comment] 2021-12-01 08:13
@pfitzseb is this actually resolved? I just ran JET, with no output in the REPL

**Comment by claforte** [comment] 2022-01-23 22:45
FWIW I also spent a couple of hours debugging this before figuring out this was a vscode+julialang issue... it would be great if this were fixed...

**Closed** 2022-03-23 17:41 UTC

**Comment by tpgillam** [comment] 2023-11-30 19:02
> woa, we already have users of this hidden integration !
> 
> You can use [`vscode_console_output`](https://aviatesk.github.io/JET.jl/dev/config/#JET.VSCode.VSCodeConfig) configuration to get REPL printing also, like:
> 
> ```julia
> julia> @report_opt vscode_console_output=stdout sum("julia")
> ```
> 
> And now I wonder `vscode_console_output` might be better to specify `stdout` by default ?

I'm not sure if this is a regression from https://github.com/julia-vscode/julia-vscode/pull/2797 , or is the "Julia: Execute Code in REPL" action intended to have different behaviour?

Running a `@report_opt ...` call with shift+enter (Execute Code) in VSCode gave no stdout output for me, but running it explicitly in the VSCode REPL did. After reading this thread I do now see that there was output going to the "Problems" tab in VSCode, but I haven't found any other cases where the behaviour of typing vs Execute Code is different.

Using `@report_opt vscode_console_output=true ...` does restore the desired (for me) behaviour; is there a way to make this the default somewhere in the settings if the current behaviour is intended?

**Comment by alex180500** [comment] 2024-04-16 14:16
I'm quoting @tpgillam! I'm getting the same behaviour!
