### ISSUE TITLE
plot pane: zoom and authomatic size adjustment

### ISSUE THREAD

**Issue by mmikhasenko** [julia-vscode/julia-vscode#1557] opened 2020-08-03 15:57 UTC
Thanks a lot for the great extension.
The transit from Atom to VS code was quite smooth indeed (four days already :)
Just a few things that I miss, I will post in the issues (enhancement, feature request)

When a large picture is drawn in the plot pane and it does not fit, one needs to scroll.
 - It would be great to have zoom buttons (+) (-) for the plot pane.
 - perhaps, moving the plot with the mouth once pressed would help
 - I liked the feature of automatic scaling of the plot to fit the pane (although, there was a drawback of loss in quality)

**Comment by davidanthoff** [comment] 2020-08-04 19:31
We should double check what the plotpane PR does on this, I have vague memories that I might have supported zooming.

**Comment by heliosdrm** [comment] 2020-08-05 22:49
duplicate of #1227 ?

**Closed** 2020-08-06 07:51 UTC
Labels: enhancement
