### ISSUE TITLE
Could Julia extension support jupyter notebook in the furture?

### ISSUE THREAD

**Issue by Lucifer-Morning-Star** [julia-vscode/julia-vscode#1025] opened 2020-03-02 11:40 UTC
Issue Type: <b>Feature Request</b>

Could Julia extension support jupyter notebook in the furture?

Extension version: 0.14.11
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.19569

**Comment by davidanthoff** [comment] 2020-03-02 23:00
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/874.

**Closed by davidanthoff** 2020-03-02 23:00 UTC
