### ISSUE TITLE
Unable to see results of a status package operation with the new notebook features

### ISSUE THREAD

**Issue by jlperla** [julia-vscode/julia-vscode#2268] opened 2021-07-05 17:37 UTC
See the attached.
![image](https://user-images.githubusercontent.com/13106721/124504559-9a56e000-dd7c-11eb-8ae9-323ae4be66b0.png)

Of course, I would prefer to do the standard 
```julia
] st
```
In a jupyter cell.

I couldn't tell if a project file was activted or not.  I seemed to be able to include a package in the project file, so maybe it is?  Also, the vscode bar did show an activated package:
![image](https://user-images.githubusercontent.com/13106721/124504728-e73ab680-dd7c-11eb-8ad2-77870b43f662.png)

but I wasn't sure if that applied to the julia terminal, the notebook, or both?

**Comment by davidanthoff** [comment] 2021-07-10 03:35
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/2250.

**Closed by davidanthoff** 2021-07-10 03:35 UTC
