### ISSUE TITLE
Basic features don't work on mac with Julia 1.2

### ISSUE THREAD

**Issue by utotch** [julia-vscode/julia-vscode#859] opened 2019-09-13 04:39 UTC
Many features don't work on Mac (Mojave) with Julia 1.2
I tried some downgraded version of the extensions, but all never worked.

[work]
* syntax highlighting
* run current line (Ctrl + Enter)

[doesn't work]
* hover help
* latex snippet
* code completion
* plot

-- my environment
[environment]
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

Name: Julia
Id: julialang.language-julia
Description: Julia Language Support
Version: 0.12.2
Publisher: julialang
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=julialang.language-julia

Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_DIR = /Applications/Julia-1.2.app/Contents/Resources/julia
  JULIA_HOME = /Applications/Julia-1.2.app/Contents/Resources/julia/bin
  JULIA_EDITOR = "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"

**Comment by torkar** [comment] 2019-09-13 14:43
I got a new MacBook Pro today. Did all the updates. Installed VSC and Julia-1.2 and the extension. At the bottom of the editor it says "Julia env: v1.2".  And then this pops up:

> The Julia Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

I set 
> "julia.executablePath": "/Applications/Julia-1.2.app/Contents/Resources/julia/bin/julia"

And I also tried to use only
> "julia.executablePath": "/Applications/Julia-1.2.app/Contents/Resources/julia/bin/"

Nothing works...

**Comment by daxinnan** [comment] 2019-09-15 09:34
So what's the solution for now, downgrade the vs code version?

**Comment by KristofferC** [comment] 2019-09-15 11:39
What does it say if you go to Output and select LanguageServer:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1282691/64921020-3685b080-d7be-11e9-83af-b10a622cae8c.png">

**Comment by torkar** [comment] 2019-09-15 11:49
Not much... and writing \lambda[tab] nothing happens...
<img width="1054" alt="Skärmavbild 2019-09-15 kl  13 47 46" src="https://user-images.githubusercontent.com/22315/64921132-8fa21400-d7bf-11e9-99ab-6acad84d3640.png">

**Comment by KristofferC** [comment] 2019-09-15 12:48
It doesn't seem like the server is crashing there.

**Comment by torkar** [comment] 2019-09-15 13:00
Agree. It doesn’t seem to crash now, but tab completion of Greek letters doesn’t work?

**Comment by torkar** [comment] 2019-09-16 13:56
But when I write "\eta = 1" and wait for a while until the wiggly red line shows up, I can then go and write \eta[tab] and now tab completion for symbols work! :) If I reopen the file the same thing happens, i.e., the symbols I've already written are there, of course, but I have to wait until the red line shows up then I can go back and write \alpha[tab] and it works.
<img width="519" alt="Skärmavbild 2019-09-16 kl  15 50 17" src="https://user-images.githubusercontent.com/22315/64963784-1a574180-d89a-11e9-9d67-8ae763d26b51.png">

**Comment by utotch** [comment] 2019-09-16 16:02
In my case, Greek letter completion totally doesn't work when I wait for a long time.

**Comment by daxinnan** [comment] 2019-09-17 03:09
all completions don't work at all.
![image](https://user-images.githubusercontent.com/26436171/65008337-99508680-d93b-11e9-8785-a6759729f819.png)

**Comment by torkar** [comment] 2019-09-17 05:12
Try this:
1. Save file as foo.jl
2. Write: \pi = 1 and then new line
3. Write: \eta = 1
4. Wait until the first line has a red wiggly line under it.
5. Go to the first line and rewrite the statement: \pi

for me the completion works after this.

**Comment by davidanthoff** [comment] 2019-12-14 20:44
I think for some of you the issue is that the initial store creation takes a long time. This is known, at some point we'll be able to fix it, for now you just need to wait.

For the other problems, I would suggest you try the next beta version of v0.13.0 we will hopefully put out soon and see if things are fixed there. I'm going to close this issue for now because it seems likely to me that whatever the root issue here is, is fixed on `master` or different enough that we would have a new root cause.

**Closed by davidanthoff** 2019-12-14 20:44 UTC
Labels: bug
