### ISSUE TITLE
Intellisense for local module on LOAD_PATH and loaded through "using" or "import"

### ISSUE THREAD

**Issue by zhopan77** [julia-vscode/julia-vscode#1127] opened 2020-04-19 15:23 UTC
Currently VSCode Julia plugin does not have intellisense for local modules on LOAD_PATH and loaded with "using" or "import". This includes:
* Data tip does not work.
* Auto-complete does not show relevant information.
* Go to definition does not work.
* Linter will complain about names not defined.

If "include" is used to load the module code first, intellisense would work; but intellisense does not work for modules loaded by "includet" under "Revise". Since loading a module using "include" or "includet" is not a recommended approach due to scope inconsistency when the module is repeatedly loaded, this is unimportant.

I noticed recently Juno added support for intellisense for local modules, regardless if it's loaded from LOAD_PATH with "using" or "import", or introduced by "include" or "includet". So technically there should be a way to do it.

From readings I do know that the recommended way of using a local module is to develop it as a package using Julia's package manager. This way intellisense should work properly. However, in practice often a big package contains many small functional blocks, and people like to put each functional block in a file as a module. Managing all of them as individual packages is not feasible, while putting all of them in one file is not scalable. So, I still see a good use case for local modules.

Actually, this is the top one of the 3 in my wish list to get our colleague to adopt Julia + VSCode as standard development environment.

FY the other two being workspace view, and a GUI profiler. All these 3 features are currently supported by Juno, but we prefer VSCode's overall performance.

**Comment by davidanthoff** [comment] 2020-04-19 15:36
This is a duplicate of https://github.com/julia-vscode/julia-vscode/issues/307, lets keep the discussion over in that issue!

**Closed by davidanthoff** 2020-04-19 15:36 UTC
