### ISSUE TITLE
In-module evaluation fails if execution is done with Ctrl+enter

### ISSUE THREAD

**Issue by ChrisRackauckas** [julia-vscode/julia-vscode#1541] opened 2020-08-01 12:51 UTC

**Comment by pfitzseb** [comment] 2020-08-01 13:13
That's by design, basically. VSCode's REPL never switches its context module and `Ctrl-Enter` by default simply copy-pastes the current line.

**Comment by ChrisRackauckas** [comment] 2020-08-01 13:15
Why would that be the default? In what case would people be wanting to re-evaluate one line of a package outside of the package module?

**Comment by pfitzseb** [comment] 2020-08-01 13:17
Well, we do plan to overhaul the keybindings very soon (see https://github.com/julia-vscode/julia-vscode/issues/1221). After that and a few startup time improvements there probably won't be any default keybinding for "Send Current Line Or Selection To REPL".

**Comment by aviatesk** [comment] 2020-08-01 13:19
This comment describes why we use <kdb>ctrl+enter</kbd> for copy-and-pasting into REPL for now: https://github.com/julia-vscode/julia-vscode/pull/1222#issuecomment-636512232

**Comment by davidanthoff** [comment] 2020-08-01 17:33
Lets close this: we have a roadmap and plan how this will be changed in other issues already.

**Closed by davidanthoff** 2020-08-01 17:33 UTC
