### ISSUE TITLE
coverage does not aggregate results across multiple `@testitem`

### ISSUE THREAD

**Issue by disberd** [julia-vscode/julia-vscode#3685] opened 2024-08-24 17:16 UTC
I have been trying the new test coverage features and it seems extremely cool, kudos for making this work!

I have noticed that in my tests so far, the coverage results is only shown for the last `@testitem` that was ran.
Is this something that can be tweaked via a setting, or is it a bug that I am experiencing?

Edit: To clarify, this also happens when I click the button to run all tests with coverage, not only when running test items manually one by one

**Comment by disberd** [comment] 2024-08-26 07:27
Here are some two videos showing the problem @davidanthoff 

full test run 1:
https://github.com/user-attachments/assets/d716c340-3e35-4e14-86a0-296047cd8497


full test run 2 (swapping test order):
https://github.com/user-attachments/assets/908adb1a-b9cc-4c05-99f6-f068e1d000a3

**Comment by davidanthoff** [comment] 2024-09-01 00:31
Just an update: I think I figured out what the problem is, I misunderstood how the VS Code API works :) Will be fixed as part of https://github.com/julia-vscode/julia-vscode/pull/3686.

**Comment by disberd** [comment] 2024-12-29 15:02
Just as a note, since I randomly checked and found that the linkd PR was merged, I tested with v0.132.1 and this specific issue does indeed seem to be solved.

#3687 is still present though

**Closed** 2024-12-29 19:39 UTC
