### ISSUE TITLE
Language Server Crash

### ISSUE THREAD

**Issue by benoitkugler** [julia-vscode/julia-vscode#849] opened 2019-09-04 09:50 UTC
Given the minimal setup

File A.jl

```
foo(cov::Int) = 1
foo(cov::Float32) = 1

function bar(x)
    b = foo(x)
end
```

File B.jl

```
include("A.jl")
```

File C.jl

```
include("A.jl")
include("B.jl")
```

I encounter the following crash

<details><summary>Language Server crash</summary>

> [ Info: Started symbol server
> [ Info: store set
> [ Info: Language Server crashed with
> [ Info: StackOverflowError()
> ERROR: LoadError: StackOverflowError:
> Stacktrace:
> [1] getindex at ./dict.jl:476 [inlined][2] get_root_method(::CSTParser.Binding, ::LanguageServerInstance, ::CSTParser.Binding, ::Array{CSTParser.Binding,1}) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/utils.jl:110
> [3] get_root_method(::CSTParser.Binding, ::LanguageServerInstance, ::CSTParser.Binding, ::Array{CSTParser.Binding,1}) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/utils.jl:111 (repeats 37345 times)
> [4] get_root_method at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/utils.jl:108 [inlined][5] infer_type(::CSTParser.Binding, ::CSTParser.Scope, ::LanguageServerInstance) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/type_inf.jl:19
> [6] add_binding(::CSTParser.EXPR, ::StaticLint.State) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:166
> [7](::StaticLint.State)(::CSTParser.EXPR) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:56
> [8](::StaticLint.State)(::CSTParser.EXPR) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:112
> [9](::StaticLint.State)(::CSTParser.EXPR) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:134 (repeats 3 times)
> [10] followinclude(::CSTParser.EXPR, ::StaticLint.State) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:209
> [11](::StaticLint.State)(::CSTParser.EXPR) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:91
> [12](::StaticLint.State)(::CSTParser.EXPR) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:134
> [13] followinclude(::CSTParser.EXPR, ::StaticLint.State) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:209
> [14](::StaticLint.State)(::CSTParser.EXPR) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:91
> [15](::StaticLint.State)(::CSTParser.EXPR) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/StaticLint.jl:134
> [16] scopepass(::LanguageServer.Document) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/StaticLint/src/server.jl:43
> [17] parse_all(::LanguageServer.Document, ::LanguageServerInstance) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/LanguageServer/src/parsing.jl:15
> [18] load_folder(::String, ::LanguageServerInstance) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/LanguageServer/src/requests/init.jl:62
> [19] process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServerInstance) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/LanguageServer/src/requests/init.jl:101
> [20] run(::LanguageServerInstance) at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/packages/LanguageServer/src/languageserverinstance.jl:47
> [21] top-level scope at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/main.jl:24
> [22] include at ./boot.jl:328 [inlined][23] include_relative(::Module, ::String) at ./loading.jl:1094
> [24] include(::Module, ::String) at ./Base.jl:31
> [25] exec_options(::Base.JLOptions) at ./client.jl:295
> [26] \_start() at ./client.jl:464
> in expression starting at /home/bkugler/.vscode/extensions/julialang.language-julia-0.12.2/scripts/languageserver/main.jl:7

</details>

From my first tests, the issue only arise when :

-   a function has (at least) two methods
-   a file is included twice (in another given file)

### The issue does not occur with the version 0.11.6

Thanks for your support and cheers for this amazing extension !

**Comment by 8uurg** [comment] 2019-09-14 19:45
I experienced this myself and it seems to be caused by a function overwriting itself at some point in the chain. The original function keeps going in this self overwriting cycle and never hits a nothing value stopping the function from terminating and causes a StackOverflow instead.

I've applied a 'fix' by performing cycle detection and jumping out if this is the case (in the method that is causing the stackoverflow):
```jl
function get_root_method(b::Binding, server, b1 = nothing, bs = Binding[])
    if b.overwrites === nothing || b == b.overwrites || !(b.overwrites isa Binding)
        return b
    elseif b.overwrites.t == getsymbolserver(server)["Core"].vals["Function"]
        if b in bs
            return b
        else
            push!(bs, b)
            return get_root_method(b.overwrites, server, b, bs)
        end
    elseif b.overwrites.t == getsymbolserver(server)["Core"].vals["DataType"]
        return b.overwrites
    else
        return b
    end
end
```
This resolves the issue (language server works!), but does not really resolve the underlying problem.
As having a cycle in this case is probably incorrect, the best fix would probably involve resolving that issue instead.

**Comment by ZacLN** [comment] 2019-12-15 13:47
I'll close this as I'm pretty sure this has been addressed by recent changes

**Closed by ZacLN** 2019-12-15 13:47 UTC
Labels: bug
