### ISSUE TITLE
UndefVarError: `execute_msg` not defined

### ISSUE THREAD

**Issue by StranoArtista** [julia-vscode/julia-vscode#3306] opened 2023-05-16 18:51 UTC
Hello there,
I have a question.
I am new at Julia.
I am using JupyterNotebook with VSCode.
I try execute readline() command in Jupyter but its not working.
I got an error: UndefVarError: execute_msg not defined
But when i try this command on PowerShell,it worked.
I can not understand where is the problem?

**Comment by Jebrano** [comment] 2023-05-21 17:55
I'm also having this problem, looking into the Stacktrace the error is from this function
```Julia
function readprompt(prompt::AbstractString; password::Bool=false)
    # TODO DA
    if !execute_msg.content["allow_stdin"]
        error("IJulia: this front-end does not implement stdin")
    end
    send_ipython(raw_input[],
                 msg_reply(execute_msg, "input_request",
                           Dict("prompt"=>prompt, "password"=>password)))
    while true
        msg = recv_ipython(raw_input[])
        if msg.header["msg_type"] == "input_reply"
            return msg.content["value"]
        else
            error("IJulia error: unknown stdin reply")
        end
    end
end
```
it seams `execute_msg` is not defined, although there is a function to define it 
```Julia
"""
Jupyter associates cells with message headers. Once a cell's execution state has
been set as to idle, it will silently drop stream messages (i.e. output to
stdout and stderr) - see https://github.com/jupyter/notebook/issues/518.
When using Interact, and a widget's state changes, a new
message header is sent to the IJulia kernel, and while Reactive
is updating Signal graph state, it's execution state is busy, meaning Jupyter
will not drop stream messages if Interact can set the header message under which
the stream messages will be sent. Hence the need for this function.
"""
function set_cur_msg(msg)
    global execute_msg = msg
end
```
I didn't see it been called, and I didn't understand this comment, so I just tried to comment the line ` if !execute_msg.content["allow_stdin"]` and the error message changed to `raw_input` is not defined. 

I guess this is a bug with IJulia, I will try to look more into it. 

also there is the comment `#TODO DA` and i have no idea what it means.

**Comment by davidanthoff** [comment] 2023-05-21 20:26
This is a duplicate of https://github.com/julia-vscode/julia-vscode/issues/2471. We just haven't implemented this. `# TODO DA` means I'm supposed to do it ;)

**Closed by davidanthoff** 2023-05-21 20:26 UTC
