### ISSUE TITLE
Ctrl+enter does not display inline result when enabled

### ISSUE THREAD

**Issue by ChrisRackauckas** [julia-vscode/julia-vscode#1540] opened 2020-08-01 12:50 UTC

**Comment by pfitzseb** [comment] 2020-08-01 13:14
That's by design. All Ctrl-Enter is supposed to do is copy-paste the current line into the REPL. I wouldn't recommend it if you can live with the initial startup time until Alt-Enter etc work.

**Comment by ChrisRackauckas** [comment] 2020-08-01 13:15
Is that a VSCode-wide thing that Ctrl+Enter is always just pasting into the terminal?

**Comment by davidanthoff** [comment] 2020-08-01 17:32
Should we close this? For now this is by design, and we have existing plans to redesign the execution keyboard shortcuts once the notebook stuff ships, so I don't think there is anything to do beyond that?

**Closed by davidanthoff** 2020-08-01 17:32 UTC

**Comment by ChrisRackauckas** [comment] 2020-08-01 18:57
Sounds great, I'll be excited for the Alt+Enter future.
