### ISSUE TITLE
Format document indent Julia comments

### ISSUE THREAD

**Issue by luboshanus** [julia-vscode/julia-vscode#1335] opened 2020-06-12 12:23 UTC
Hi, 
I have a question/concern about the formating of julia code. On mac I use  `alt + shift + F` and the code get formated by the julia extension, which is in most cases great.
I usually use it for ugly code written by someone else to have it readable. And if you have functions written with no indentation, such as:
```julia
function xyz(x)
# comment not indented
x = x + x
return(x)
end
```
it formats the important parts of the code well. However, the code is formated well it does not indent comments. Result is:
```julia
function xyz(x)
# comment not indented
    x = x + x
    return(x)
end
```
The comment is still on the first column in the script. And this is a mess when you have comments in inner loops of inner loops, comments remain on the left = ugly.

Is there any easy way to implement an improvement? Thanks a lot!

**Comment by davidanthoff** [comment] 2020-06-12 21:40
Duplicate of https://github.com/julia-vscode/DocumentFormat.jl/issues/49.

**Closed by davidanthoff** 2020-06-12 21:40 UTC
