### ISSUE TITLE
Latex completion not working

### ISSUE THREAD

**Issue by torkar** [julia-vscode/julia-vscode#613] opened 2018-11-28 20:30 UTC
Hi,

I've installed 0.11.0-beta2 and run it with Code 1.29.1 and Julia 1.02 on OS X. For some reason, when I type \beta[tab] in my Julia REPL it works, but if I open a file foo.jl and type it there it doesn't. Have I messed something up (can I check that somehow?) or is 0.11.0-beta2 not supporting this?

Otherwise, thanks for an excellent extension and the work you put in this!

**Comment by torkar** [comment] 2018-11-28 21:06
I've restarted and all, and I noticed this now:

> Could not start the julia language server. Make sure the configuration setting julia.executablePath points to the julia binary.

(it points to the executable)

And when trying to run the REPL I get:
"The terminal process terminated with exit code: 1"
And in the terminal I see a stacktrace flying by before this message:
"ERROR: LoadError: UndefVarError: Display not defined"

**Comment by torkar** [comment] 2018-11-28 21:20
These are the only packages I have installed:
<img width="172" alt="screenshot 2018-11-28 at 22 19 40" src="https://user-images.githubusercontent.com/22315/49182885-c22b6f00-f35b-11e8-8d02-2ad492b0e720.png">

**Comment by davidanthoff** [comment] 2018-11-29 17:49
The language server will take a long time the first time you start it before it is operational, can you just give it some time and see whether it then starts to work? A couple minutes...

**Comment by torkar** [comment] 2018-11-29 17:52
The server starts immediately now (used Atom today). However, \beta[tab] does not produce a beta?

**Comment by davidanthoff** [comment] 2018-11-30 00:53
@ZacLN any idea?

**Comment by ZacLN** [comment] 2018-11-30 07:09
Is this vscode or Atom? Do other language features work (i.e. hovers)? Do other completions work?

**Comment by torkar** [comment] 2018-11-30 15:43
When I open VS code (and 0.11.0-beta2) and type \beta[tab] the following happens for 20 sek:
<img width="604" alt="screenshot 2018-11-30 at 16 39 38" src="https://user-images.githubusercontent.com/22315/49298956-e2277380-f4be-11e8-921f-e2385af187ea.png">

And then this happens (notice also bottom right corner):
<img width="1174" alt="screenshot 2018-11-30 at 16 41 19" src="https://user-images.githubusercontent.com/22315/49298985-f3708000-f4be-11e8-98e2-8da80d4c0f64.png">

**Comment by babatundeladega** [comment] 2018-12-10 00:49
Thank you for working on this project.

Will the “Could not start the julia language server” bug observed on Julia 1.0/MacOS/VS Code be address by v0.11.0 GA?

Also, wondering if you’d suggest using Atom in the interim. Just getting started with Julia. 
Cheers

**Comment by babatundeladega** [comment] 2018-12-14 18:36
Thank you.

> “You're a real prince. You're a gentleman and a scholar,"

 Arnavs.

**Comment by valeraiibaidin** [comment] 2019-02-10 17:29
Hi, I use VS code, and I very like it, it's faster than Atom. 
Unfortunately, \bate + "tab" don't work. 
I use Win, Julialang 0.11.4 and last version Julia.

Should it work or not?

**Comment by floringogianu** [comment] 2019-02-20 15:16
I can confirm latex completion is not working on `vscode 1.31.1`, `julia-vscode 0.11.4`, `julia 1.1.0`. No autocompletion either. Code block execution is working fine.

**Comment by floringogianu** [comment] 2019-02-21 07:26
@davidanthoff this is actually related to https://github.com/JuliaEditorSupport/julia-vscode/issues/647, right?

**Comment by davidanthoff** [comment] 2019-02-21 15:59
Probably...

**Comment by floringogianu** [comment] 2019-02-22 15:37
Thanks, I compiled `julia 1.0.3` and I can confirm latex completion, linter and autocomplete are working.

**Comment by stevengj** [comment] 2019-03-26 15:23
Presumably you can use https://marketplace.visualstudio.com/items?itemName=oijaz.unicode-latex as a workaround.

**Comment by davidanthoff** [comment] 2019-03-26 21:34
We used to have the latex support not in the language server but as snippets (see [here](https://github.com/JuliaEditorSupport/julia-vscode/blob/v0.4.0/snippets/latex_snippets.json)). I don't remember why we changed that. @ZacLN, do you remember?

**Comment by cscherrer** [comment] 2019-04-21 23:55
I'm not sure if this is related, but LaTeX completion is sometimes doesn't work for me. Here's a particularly weird example:
```julia
εₓ ~ Normal(0,1)
x = μ .* \varepsil<TAB>

x
```

The `<TAB>` inserts a literal `'\t'`. Oddly enough, if I remove the `"\nx"` at the end everything is back to normal (one `'\n'` is ok, two is not).

I'm running 0.11.5 on this setup:
```
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-12T08:59:47.459Z
Electron: 4.1.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.30-electron.0
OS: Linux x64 4.19.34-1-MANJARO
```

**Comment by alecloudenback** [comment] 2019-06-14 23:07
For those coming looking for a workaround, I've found the [Fast Unicode Math Characters](https://marketplace.visualstudio.com/items?itemName=GuidoTapia2.unicode-math-vscode) a pretty natural replacement for this functionality.

**Comment by musm** [comment] 2019-06-18 14:26
It would be nice if the latex in the repl and vscode worked the same.

`\mu<tab> (just inserts space)` 

@alecloudenback  that extension seems to fix things

**Comment by kbarros** [comment] 2019-08-26 03:10
Hi, with version 0.12.1 on MacOS this works:
`\mu<tab>`

But this doesn't:
`\^2<tab>`.

**Comment by alexeypetrushin** [comment] 2020-01-29 19:51
Unicode autocomplete worked in my previous version of VSCode + Julia (don't remember the version sadly). But now with julia extension v. `0.13.1` it's not working.`\alpha + TAB` does nothing.

If that helped - I supplied fake path to julia executable in Julia VSCode Extension, to avoid CPU load.

**Comment by ZacLN** [comment] 2020-01-29 21:50
Somewhat unsurprisingly, supplying a fake path means the extension won't work

**Comment by alexeypetrushin** [comment] 2020-01-30 08:04
Does unicode autocompletion depend on julia executable?

**Comment by ZacLN** [comment] 2020-01-30 08:12
Yep

**Comment by stevengj** [comment] 2020-01-30 13:23
It seems like you should just pull out the unicode tab completion and use https://marketplace.visualstudio.com/items?itemName=oijaz.unicode-latex or similar.

**Comment by vomout** [comment] 2020-01-30 14:15
I tried the unicode tab-completion before but had some trouble with it… messing up writing LateX itself probably. Maybe it has improved, maybe I should try it again. But, yeah, these fancy packages with “smart” features are more trouble than they're worth. I just need syntax highlighting, basic auto-indentation (new block => indent next line when I press enter, otherwise keep same level), and unicode expansion. tab-completion of other symbols is nice, but not essential. Any sort of auto-bracketing and so on (ahem, LaTeX-workshop) just rips my eyes out of their sockets. And right now the Julia package is producing a list of 200 supposed "errors" (”missing reference” that it's too bloody stupid to figure out) that intermingle with the proper LaTeX build errors in the same workspace.

**Comment by s-valent** [comment] 2020-07-07 15:12
I should probably point out that the problem still exists. Sometimes after launching VS Code autocompletions start working but then break after short period of time. And I found a few julia processes in terminal/top, which where most likely spawned by code, but continued working after code is shut down (saw this multiple times)

**Comment by kapple19** [comment] 2020-11-16 15:02
I think this may merit opening a different issue, but in `.jmd` files, tab completion works outside of code blocks, but not inside them. Any thoughts?

**Comment by ericgreveson** [comment] 2020-11-30 21:57
Sorry to leave a fairly unhelpful "me too" comment, but I have experienced the same problem using Julia 1.5.3, Visual Studio Code 1.51.1, julia-vscode 1.0.9 and 1.0.10 - worked around this with suggestion above to use the Fast Unicode Math Characters plugin.

**Comment by highflyer737** [comment] 2020-12-03 20:17
I've been seeing this too on and off. I'm currently using 1.0.10 with vs-code 1.51.1 and 1.52.0-insider, but I've seen it before with other versions as well.

I (accidentally) just discovered is that if there is an open docstring it doesn't complete, but works as soon as the docstring is closed. So, I'd open a file and start writing documentation for a new function:

>"""
>    myfun(a)
>
>Nice documentation goes here, m\\^2\<tab\>

Would produce nothing, but:

>"""
>    myfun(a)
>
>Nice documentation goes here m\\^2\<tab\>
>"""

Completes as expected, as long as the docstring is closed _before_ typing m\\^2\<tab\>

Not sure if this is a bug or by design.

**Comment by leventov** [comment] 2020-12-27 11:06
@ericgreveson

> Sorry to leave a fairly unhelpful "me too" comment, but I have experienced the same problem using Julia 1.5.3, Visual Studio Code 1.51.1, julia-vscode 1.0.9 and 1.0.10 - worked around this with suggestion above to use the Fast Unicode Math Characters plugin.

Thanks! Have you been able to have dropdown with available mnemonics when you start typing `\...`?

**Comment by pfitzseb** [comment] 2020-12-28 09:05
Just wanted to note once again that this is a symptom of the language server not starting up correctly.

**Comment by ericgreveson** [comment] 2020-12-28 17:11
@leventov - I have now updated to the Julia Insider 1.0.11 plugin (also I'm on VS Code 1.52.1 now, if that makes a difference), and it seems like both issues are fixed (language server starts and I can now type `\...` and get the dropdown without needing any other plugins). So as mentioned above, I guess the mnemonics issue is dependent on the language server issue.

**Comment by JontySinai** [comment] 2021-01-05 11:22
Ensuring that tab completion is on in the Julia extension settings worked for me. Add this to your settings.json:

```
"[julia]": {
        
    "editor.tabCompletion": "on",
        "editor.quickSuggestions": true

```

**Comment by davidanthoff** [comment] 2021-02-21 03:49
I think we have a couple of reports here now that this works in newer versions, so I'm going to close this issue.

**Closed by davidanthoff** 2021-02-21 03:49 UTC
Labels: area-ls-completion, bug
