### ISSUE TITLE
Julia-insider causes git settings to "disappear" in recent vscode build

### ISSUE THREAD

**Issue by asampal** [julia-vscode/julia-vscode#2265] opened 2021-07-01 07:05 UTC
Uninstalling this extension brought back git functionality.

Please see https://github.com/microsoft/vscode/issues/127736

**Comment by davidanthoff** [comment] 2021-07-01 15:31
Thanks for reporting! I know what the problem is, working on getting out a new build ASAP.

**Comment by davidanthoff** [comment] 2021-07-02 22:58
I think this should be fixed now, if not please let me know.

**Closed by davidanthoff** 2021-07-02 22:58 UTC
Labels: Showstopper, bug
