### ISSUE TITLE
Debugger continues to breakpoint when if statement is false

### ISSUE THREAD

**Issue by mpeters2** [julia-vscode/julia-vscode#3533] opened 2024-02-11 19:00 UTC
In the screen shot below, the `if` statement evaluates to `false` and the `println()` on line 881 should not print. But I can get the debugger to stop on line 882, as shown in the screen shot.

 If I run it in the REPL: the print statement never prints. (`if` evaluates to `false`).
 If I run in the debugger with a breakpoint only on line 882, it never stops at the breakpoint, indicating that the `if` evaluated to `false`.

BUT, if I add a breakpoint at 880, then hit continue after the debugger stops at 880, the debugger goes to the next breakpoint (line 882), implying that the if statement evaluated as true. But, line 881 never prints in that situation, indicating that the if statement must have evaluated to false, yet, as you can see below, the debugger has gone to line 882! So all of this time I’m thinking that the if statement had evaluated as `true`, when it had not. In addition, if I then click on continue, the function `setPos()` on line 882 never runs, but the debugger stopping on line 882 suggests that it should.

<img width="726" alt="Screenshot 2024-02-11 at 11 46 29 AM" src="https://github.com/julia-vscode/julia-vscode/assets/26334076/1c937b36-042d-4893-b991-621b4873d1fd">

**Comment by BenPH** [comment] 2024-02-12 13:02
Sounds like a duplicate of https://github.com/julia-vscode/julia-vscode/issues/2693. Check out the response there.

**Closed** 2024-02-12 14:00 UTC
