### ISSUE TITLE
Running Jupyter Notebooks with Julia Kernel on M1 Mac

### ISSUE THREAD

**Issue by daler6** [julia-vscode/julia-vscode#2386] opened 2021-08-20 18:00 UTC
I submitted the following under the vscode-jupyter issue area and was informed that it was a duplicate of issue #5206 there. After a couple of iterations, though, it seems that the problem may be with the Julia extension, so I was asked to resubmit here.

**Environment data**
VS Code version: 1.59
Jupyter Extension version (available under the Extensions sidebar): 2021.8.1236758218
Python Extension version (available under the Extensions sidebar): 2021.8.1147840270
OS (Windows | Mac | Linux distro) and version: macOS Big Sur 11.5.2
Jupyter server running: Local | Remote | N/A
Julia extension: 1.3.30, with Julia:Notebook Controller option checked

**Expected behaviour**
When I open an existing or new Jupyter notebook and select the Julia kernel, everything should work fine.

**Actual behaviour**
I am told that I need to install the Python extension for this to work. Once I install that extension, it does work.

This seems to only happen on my new M1 MacMini. On my MacBookPro with an Intel chip running the same setup, I do not need to install the Python extension to run Jupyter Notebooks.

**Comment by DonJayamanne** [comment] 2021-08-21 17:02
@davidanthoff to be clear, the problem isn't with Julia extension.
Today we use zmq to communicate with the kernels, and we don't have a node build of zmq for Mac m1, hence we cannot use zmq with node, the fall back is to use jupyter, which requires users to install python (that will internally download and build zmq).

As a when around for all of this, my suggestion to the user is to install the Julia extension and use it's built in support for notebooks 

Is it public or still in preview? With the Julia extension, user works not have to use the jupyter extension to run Julia code in notebooks.

**Comment by davidanthoff** [comment] 2021-08-21 17:38
@DonJayamanne we are shipping the notebook stuff in the released extension, but behind a feature flag. We are just waiting to resolve https://github.com/julia-vscode/julia-vscode/issues/2256, and then we'll just remove the feature flag and will have the support always-on.

**Comment by davidanthoff** [comment] 2021-08-21 17:39
Ok, and I'm going to close this issue here, given that this is not a problem on our end :)

**Closed by davidanthoff** 2021-08-21 17:39 UTC

**Comment by daler6** [comment] 2021-08-22 17:42
@davidanthoff I want to make sure I am completely clear. Right now I am able to create and use Jupyter notebooks with a Julia kernal on both a Mac with an Intel chip and a Mac with an M1 chip. In both cases, I need to make sure that the Julia:Notebook Controller setting is checked. For the Mac with the M1 chip, I also need to install the Python extension; I do not need to do this for the Mac with the Intel chip.

When you resolve #2256, what exactly will change? Will users no longer need to set the Julia: Notebook Controller setting? Will users with a Mac with the M1 chip be able to use Jupyter notebooks without needing to install the Python extension? Finally, what is the timeline on resolving this issue and releasing the next version of the Julia extension?

Thanks.

**Comment by davidanthoff** [comment] 2021-08-22 19:16
Oh, hi @daler6, didn't even realize who you were for a while :)

I'm not entirely sure what you are doing, but if Python shows up in your workflow, then you are not using the notebook controller from our extension, but instead you are going via the Jupyter extension. Our stuff has no dependency on anything Python at all.

Once we resolve #2256 we will remove the notebook controller configuration from the extension and just enable the notebook controller always.

**Comment by daler6** [comment] 2021-08-22 22:18
Aha, I see the problem! I do not even need to install the Jupyter extension. That simplifies things a lot. I was able to open and use an existing notebook. However, now I am having trouble figuring out how to open a new, blank notebook.

**Comment by davidanthoff** [comment] 2021-08-22 22:30
The new notebook command is unfortunately only present in the Jupyter extension... There are a number of rough edges around all of this that we're still trying to iron out, will probably still take a little while :)

**Comment by daler6** [comment] 2021-08-22 22:39
OK, I have found a couple of workarounds in any case.

QUICK
1. Open a new file by right clicking in the Explorer window and giving the new file the .ipynb extension.

SLOW
1. Open a new file by selecting File, New File.
2. Save the file with the .ipynb extension.
3. Close and reopen the file; otherwise you do not get the Notebook "interface".

If there is another way, please let me know.

By the way, I am going through all this because on Tuesday, I start teaching a class to upper level undergraduates on Data Science with Julia. So, please expect to see other questions coming your way. :)

**Comment by davidanthoff** [comment] 2021-08-23 00:49
I think the other option is to install the Jupyter extension and then there is a command to create a new Jupyter notebook.

Very exciting to hear about the course!
