### ISSUE TITLE
Data Explorer / Variables Pane

### ISSUE THREAD

**Issue by rwatts3** [julia-vscode/julia-vscode#538] opened 2018-08-10 19:03 UTC
Are there plans to support a data explorer, or variables view
where one would execute a command and have the ability to explore the variable.

Similar to how Juno/Julia Client in Atom has the Workspace pane.

**Comment by davidanthoff** [comment] 2018-08-10 22:02
Yes, plans and we had a prototype working. No promise about a timeline.

**Comment by grantmcdermott** [comment] 2019-11-06 22:07
Would it be possible to support this through the new(ish) variable explorer in the Jupyter session? https://vscode-westus.azurewebsites.net/docs/python/jupyter-support#_variable-explorer-and-data-viewer

(Mostly commenting so I can watch this issue.)

**Comment by davidanthoff** [comment] 2019-11-14 04:47
Maybe, not sure... I think right now we have such a backlog of real bugs (and very little time on either @ZacLN's or my end) that this feature will probably be on the back burner for a while :)

**Comment by davidanthoff** [comment] 2020-05-11 09:49
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/516.

**Closed by davidanthoff** 2020-05-11 09:49 UTC
Labels: enhancement
