### ISSUE TITLE
REPL not found

### ISSUE THREAD

**Issue by projekter** [julia-vscode/julia-vscode#3656] opened 2024-07-26 11:38 UTC
The latest update does not longer allow to enter code that was typed in the REPL. Start a Julia session and type
```julia
function test()
    return 1
end
@enter test()
```
then, with 1.83.2 (the previous stable version), a new source code window titled `REPL` was opened which contained the `test()` call which you could then choose to step into, over, or into a particular part if it was more complicated.
Starting from at least 1.84.1 [1.84.0 is not available via VS Code], the `REPL` source code window opens with no content and the progress indicator running and if I cancel the debugger, the editor contains the text `Could not load source 'REPL': Canceled.`.
Starting from at least 1.90.1 [1.89.1 is as 1.84.1], the `REPL` tab opens, the progress indicator is there for <1s, then the same cancel-related text appears as before and Julia crashes with the error `KeyError: key 0 not found`. Due to VS Code's immediate closing of the terminal window, I can only make a screenshot of the stacktrace:
![grafik](https://github.com/user-attachments/assets/1d936a07-ec5b-4bba-891b-d7145daa69bc)
The same exception was reported in #3651, though there it appears to be related to a particular function, not that whatever function was defined in the REPL console.
_Edit_: In preparing a second bug report for a different problem (which was the cause for finding this one), the problem seems to also occur when functions are defined elsewhere, because the call `test()` itself is "defined" in the REPL. So basically, any `@enter`-related functionality is broken.

**Comment by davidanthoff** [comment] 2024-07-27 15:08
This is a duplicate of https://github.com/julia-vscode/julia-vscode/issues/3651. I have a fix, should ship soon.

**Closed by davidanthoff** 2024-07-27 15:08 UTC
