### ISSUE TITLE
Terminal is showing result of previous command 

### ISSUE THREAD

**Issue by kafisatz** [julia-vscode/julia-vscode#2358] opened 2021-08-11 08:07 UTC
Hi

When I execute a command (CTRL + Enter, or typing in the REPL) the result of the previous command is shown. 
I am not quite sure how to better describe this. 
Please have a look at the gif.
The first 'result' of 11 must have been the result of a calculation further above.

On a new session this does not happen.
However, I run into this frequently these days. Usually after 'working a bit' (i.e. executing several code blocks with CTRL+Enter)

![vscode](https://user-images.githubusercontent.com/15026865/128993181-803effec-3f49-4298-93aa-9a90b05908a2.gif)

Any idea why this is happening? 
I am on Windows 10.

**Comment by pfitzseb** [comment] 2021-08-11 08:09
Historically this is usually caused by Revise, but that bug should've been fixed in recent versions. It's also possible that we have a similar bug in the extension...

What version of the extension are you on? Are you using Revise?

**Comment by kafisatz** [comment] 2021-08-11 08:11
Yes, I am using Revise. I my main environment  [295af30f] Revise v3.1.17
I am using the Julia extension v1.3.27

**Comment by pfitzseb** [comment] 2021-08-11 08:16
Can you check whether the bug is reproducible without Revise?

**Comment by kafisatz** [comment] 2021-08-11 08:19
I can try, but I am actually not sure how to trigger it :)

**Comment by kafisatz** [comment] 2021-09-27 20:14
I don't think this is a vscode issue. It seems tim holy has fixed this, although i have not tested this myself yet. Feel free to close the issue

**Closed** 2021-11-04 17:39 UTC
Labels: needs more info
