### ISSUE TITLE
precompilation error because Test environment is not updated?

### ISSUE THREAD

**Issue by lmiq** [julia-vscode/julia-vscode#3200] opened 2022-11-01 14:16 UTC
The issue is the following. I have a package that **did not* depend on the `CellListMap` package. Then I added `using CellListMap` to the main package module, and tried to run a `@testitem`. The test failed, because the package could not be precompiled, as I had forgot to add `CellListMap` as dependency of the package. So far, everything expected.

Next, I added `CellListMap` to the environment, which updated the `Project.toml` file, as usual, added the compat entry. Effectively, now I can `using` my package from the REPL, because everything is fine. 

Now the issu: The `@testitem` continues to fail as if I had not updated the envrionment and Project.toml files. I tried to `instantiate`, `resolve`, etc, and nothing did the trick. The snapshot illustrates the current state:

![image](https://user-images.githubusercontent.com/31046348/199253634-f562bf4e-2aaf-4fef-a970-d3d0ebbcf77a.png)

As it can be seen, the package loads fine in the REPL, but the testitem fails because it cannot precompile the package.

The error message in the `JuliaTestserver` log is below, but it is misleading, as the files are already updated to the new dependency:

```
ERROR: LoadError: ArgumentError: Package ComplexMixtures does not have CellListMap in its dependencies:
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have ComplexMixtures checked out for development and have
  added CellListMap as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with ComplexMixtures
Stacktrace:
 [1] macro expansion
   @ ./loading.jl:1167 [inlined]
 [2] macro expansion
   @ ./lock.jl:223 [inlined]
 [3] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144
 [4] include
   @ ./Base.jl:419 [inlined]
 [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1554
 [6] top-level scope
   @ stdin:1
in expression starting at /home/leandro/.julia/dev/ComplexMixtures/src/ComplexMixtures.jl:1
in expression starting at stdin:1
```

Thus, it seems that some internal environment that was cached is not updated.

Now I restarted VSCode to continue working, and the `@testitem` works, so I cannot now reproduce the problem. But maybe this provides some info about an underlying issue that can be easily solved.

**Comment by davidanthoff** [comment] 2024-06-06 23:16
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/3022.

**Closed by davidanthoff** 2024-06-06 23:16 UTC
